# Generated by Django 6.0.7 on 2026-09-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_teachermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
